# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    #container:
    #  image:  cirrusci/flutter:v1.7.8-hotfix.4
    #  options: --user root

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build the .lua file
      - name: Run the build script
        run: ./build.sh
        
      # Check for syntax errors
      - name: Syntax check
        run: ./syntaxChecker.sh
        
      # Push changes to the edited branch
      - name: Push changes to the ${{github.ref}} branch
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{secrets.GITHUB_TOKEN}}
         branch: ${{github.ref}}
